### ISSUE TITLE
Various elements broken on mobile

### ISSUE THREAD

**Issue by edwellbrook** [edwellbrook/minami#1]
Sounds like there are various parts of the theme that are broken on mobile devices.

---
See: https://github.com/edwellbrook/node-tvdb/issues/87

**Comment by giacomocerquone** [comment]
You can assign it to me, I'm working on it 😃

**Comment by edwellbrook** [comment]
Unfortunately GitHub won't let me assign this to you but, thanks for working on it! Looking forward to your PR. Let me know if you need anything 😄

**Comment by giacomocerquone** [comment]
Solved 😉
